# tmux agent backend image (AGENT_BACKEND=tmux): the universal sandbox base +
# tmux + ttyd + pre-accepted first-launch gates, so an interactive `claude` can
# be driven by tmux send-keys and stream structured events via HTTP hooks.
# See docs/tmux-backend-spike.md and app/domain/agent/tmux_provider.py.
#
# BUILD (context = backend/sandbox so the base image is available):
#   docker build -f backend/sandbox/tmux.Dockerfile -t cheesex-agent-tmux:latest backend/sandbox
#
# CI passes the base it just pushed as BASE_IMAGE, so the two images can never
# drift apart; the default keeps the local build working unchanged.
ARG BASE_IMAGE=cheesex-agent-sandbox:latest
FROM ${BASE_IMAGE}

# tmux (drive the interactive session) + ttyd (read-only web terminal mirror for
# 施工现场). ttyd is a static binary — not packaged for debian.
USER root
RUN apt-get update && apt-get install -y --no-install-recommends tmux \
    && rm -rf /var/lib/apt/lists/*
RUN ARCH="$(uname -m)" && \
    curl -fsSL "https://github.com/tsl0922/ttyd/releases/download/1.7.7/ttyd.${ARCH}" \
      -o /usr/local/bin/ttyd && chmod +x /usr/local/bin/ttyd && ttyd --version

# Pre-accept the first-launch gates that would otherwise eat the first prompt of
# a new interactive session (spike 坑 #1). Verified against Claude Code 2.1.x:
#   ~/.claude.json  top-level : hasCompletedOnboarding, autoUpdates=false
#                   projects["/work"] : hasTrustDialogAccepted, hasCompletedProjectOnboarding
#   ~/.claude/settings.json   : skipDangerousModePermissionPrompt  (← written by
#                   the provider into the MOUNTED session dir, not baked here,
#                   because that dir is a bind mount at runtime).
# bypassPermissionsModeAccepted is kept as a legacy fallback (still honored; it
# migrates to skipDangerousModePermissionPrompt on first run).
RUN printf '%s\n' \
      '{"hasCompletedOnboarding":true,"autoUpdates":false,"bypassPermissionsModeAccepted":true,"projects":{"/work":{"hasTrustDialogAccepted":true,"hasCompletedProjectOnboarding":true}}}' \
      > /home/node/.claude.json \
    && chown node:node /home/node/.claude.json

# Hook forwarder: Claude Code's built-in HTTP hooks BLOCK non-loopback targets
# (host.docker.internal resolves to a private IP → "HTTP hook blocked"), so we
# use COMMAND hooks that run this script. It reads the hook JSON on stdin and
# POSTs it to the backend (URL + token from the container env), which has no such
# restriction. Exit 0 with empty stdout = "no decision" → the tool proceeds.
#
# Single source of truth: hooks_substrate.CHEESE_HOOK_SCRIPT (the SAME string the
# device launcher writes at runtime). The committed `cheese-hook` file is
# regenerated by `scripts/gen-sandbox-assets.py` and drift-guarded by
# test_hooks_substrate.py — so the baked image and the remote path can't diverge.
COPY cheese-hook /usr/local/bin/cheese-hook
RUN chmod +x /usr/local/bin/cheese-hook

USER node
WORKDIR /work
