"""The standard templates a room can start a document from.

Each is a real Office file (in `templates/`, regenerated by
`scripts/build_document_templates.py`): a new document made from one is a copy
of it, opened in the editor like any other room file. What a template gives is
structure and styles — headings, a styled table, a chart already wired to its
data — with 【占位】 where the content goes.
"""

from dataclasses import dataclass
from pathlib import Path

_DIR = Path(__file__).resolve().parent / "templates"


@dataclass(frozen=True)
class Template:
    id: str
    name: str
    suffix: str
    about: str

    def as_dict(self) -> dict:
        return {
            "id": self.id,
            "name": self.name,
            "suffix": self.suffix,
            "about": self.about,
        }


TEMPLATES = (
    Template(
        "report",
        "报告",
        "docx",
        "摘要、背景、发现、数据表、结论与参考来源",
    ),
    Template(
        "proposal",
        "方案",
        "docx",
        "问题、目标与范围、方案设计、实施计划表、风险",
    ),
    Template(
        "weekly",
        "周报",
        "docx",
        "本周完成、进行中、问题与支持、下周计划",
    ),
    Template(
        "project-deck",
        "项目汇报",
        "pptx",
        "封面加 5 页：目标进展、成果、风险、计划、支持",
    ),
    Template(
        "research-deck",
        "调研汇报",
        "pptx",
        "封面加 5 页：问题方法、发现、对比、结论、来源",
    ),
    Template(
        "analysis",
        "数据统计分析",
        "xlsx",
        "数据表、自动汇总公式、柱状图、口径说明",
    ),
)


def find(template_id: str) -> Template | None:
    return next((t for t in TEMPLATES if t.id == template_id), None)


def template_bytes(template: Template) -> bytes:
    return (_DIR / f"{template.id}.{template.suffix}").read_bytes()
