#!/usr/bin/env python3
"""Refresh the frozen baselines in `backend/.importlinter`.

    cd backend && uv run python scripts/boundary_baseline.py --update
    cd backend && uv run python scripts/boundary_baseline.py --update --freeze-new
    cd backend && uv run python scripts/boundary_baseline.py          # report only

WHAT IT DOES. Runs the three contracts with the baselines stripped out, reads
the violations off the results, and rewrites each contract's `ignore_imports`
block so that exactly those violations are frozen — one line per pair of
modules, `importer -> imported`, sorted, no wildcards (the format cannot express
one that this script would write, and `check_boundaries.py` refuses to run with
one anyway: what this writes is not the only thing that can be in the block).

`--update` IS SHRINK-ONLY. Entries that stopped matching anything are dropped —
paying a debt down must not go red. Entries that would have to be *added* are
not written: it prints them and exits 1. New violations are the whole point of
the check, so accepting one is a decision somebody has to make on purpose, by
typing `--freeze-new` (which prints every line it is about to freeze, so the
diff of a commit that froze something says what it was).

The rewrite is verified: after writing, it runs `check_boundaries.py` on the new
file and requires exit 0. If the file does not converge, the original is put
back and the script exits 2 — a refresh that leaves the check red is worse than
no refresh, because it looks like it worked.

Exit 0 wrote something / nothing had changed, 1 new violations need a decision,
2 could not judge or could not converge.
"""

from __future__ import annotations

import argparse
import re
import sys
import tempfile
from pathlib import Path

HERE = Path(__file__).resolve()
BACKEND_ROOT = HERE.parents[1]
CONFIG_PATH = BACKEND_ROOT / ".importlinter"

#: Same guard as check_boundaries.py: a declaration that lost a contract must
#: not be "refreshed" into a smaller check.
CONTRACT_IDS = ("api-domain-core", "routes-touch-no-models", "domains-acyclic")

MARKER = "# --- frozen: existing violations, generated by scripts/boundary_baseline.py"
SUBHEAD = (
    "# Refresh with `--update` (drops entries that no longer match; new ones need "
    "`--freeze-new`)."
)
HEADER_RE = re.compile(r"^\[importlinter(?::contract:(?P<id>[^\]]+))?\]\s*$")

OK, NEEDS_DECISION, CANNOT_JUDGE = 0, 1, 2


class ConfigShapeError(Exception):
    """The file has a frozen block this script will not guess its way around."""


# ---------------------------------------------------------------------------
# Reading and writing the file. A section is `[header]` plus the lines up to the
# next header. Prose may sit above a section's options; the frozen block is
# always the last thing in its section; anything unexpected after the marker is
# an error rather than something to silently drop.
# ---------------------------------------------------------------------------


def sections(text: str) -> tuple[str, list[tuple[str, str | None, list[str]]]]:
    """(preamble, [(header, contract id or None, body lines)])."""
    lines = text.split("\n")
    heads = [i for i, line in enumerate(lines) if HEADER_RE.match(line)]
    if not heads:
        raise ConfigShapeError("no [importlinter] section at all")
    preamble = "\n".join(lines[: heads[0]])
    out = []
    for position, start in enumerate(heads):
        end = heads[position + 1] if position + 1 < len(heads) else len(lines)
        match = HEADER_RE.match(lines[start])
        out.append((lines[start], match.group("id"), lines[start + 1 : end]))
    return preamble, out


def split_block(body: list[str]) -> tuple[list[str], list[str]]:
    """Split a section body into (lines to keep, frozen entries)."""
    index = next(
        (i for i, line in enumerate(body) if line.strip() == MARKER.strip()), None
    )
    if index is None:
        kept = list(body)
        while kept and not kept[-1].strip():
            kept.pop()
        return kept, []

    kept = list(body[:index])
    tail = [line for line in body[index:] if line.strip()]
    if tail[:2] != [MARKER, SUBHEAD]:
        raise ConfigShapeError(
            f"the generated block after {MARKER!r} is not the shape this script "
            "writes; it will not overwrite it"
        )
    rest = tail[2:]
    entries: list[str] = []
    if rest:
        if rest[0].strip() != "ignore_imports =":
            raise ConfigShapeError(
                f"expected `ignore_imports =` after the generated block header, "
                f"found {rest[0]!r}"
            )
        for line in rest[1:]:
            if not line.startswith("    ") or not line.strip():
                raise ConfigShapeError(
                    f"{line!r} follows the frozen entries but is not one; the "
                    "generated block must be the last thing in its section"
                )
            entries.append(line.strip())
    while kept and not kept[-1].strip():
        kept.pop()
    return kept, entries


def render_block(entries: list[str]) -> list[str]:
    block = [MARKER, SUBHEAD]
    if entries:
        block.append("ignore_imports =")
        block.extend(f"    {entry}" for entry in entries)
    return block


def read_entries(text: str) -> dict[str, list[str]]:
    """The entries currently frozen in the file, per contract id."""
    _, parsed = sections(text)
    frozen = {}
    for _header, contract_id, body in parsed:
        if contract_id is None:
            continue
        _, entries = split_block(body)
        frozen[contract_id] = entries
    return frozen


def strip_baselines(text: str) -> str:
    """The same file with every frozen block removed — the contracts as declared."""
    preamble, parsed = sections(text)
    chunks = [preamble.rstrip("\n")]
    for header, _, body in parsed:
        kept, _ = split_block(body)
        chunks.append("\n".join([header, *kept]))
    return "\n\n".join(chunk.rstrip("\n") for chunk in chunks) + "\n"


def write_baselines(text: str, frozen: dict[str, list[str]]) -> str:
    preamble, parsed = sections(text)
    chunks = [preamble.rstrip("\n")]
    for header, contract_id, body in parsed:
        kept, _ = split_block(body)
        if contract_id is None:
            chunks.append("\n".join([header, *kept]).rstrip("\n"))
            continue
        if contract_id not in frozen:
            raise ConfigShapeError(
                f"[importlinter:contract:{contract_id}] is not one of the contracts "
                f"this script knows (it knows {list(frozen)})"
            )
        block = render_block(sorted(frozen[contract_id]))
        chunks.append("\n".join([header, *kept, "", *block]).rstrip("\n"))
    return "\n\n".join(chunks) + "\n"


# ---------------------------------------------------------------------------
# Reading the violations off a run.
# ---------------------------------------------------------------------------


def entries_from_metadata(metadata: dict) -> list[str]:
    """The frozen expression for each violation in one contract's metadata.

    One line per *direct* import, because that is what `ignore_imports` matches:
    the layer contract reports chains of imports, and removing a link from a
    chain is what silences it. Exceptions are per module pair, so every line of
    each chain is frozen.
    """
    edges: set[tuple[str, str]] = set()

    # layers: invalid_dependencies -> routes -> chain -> links
    for dependency in metadata.get("invalid_dependencies", []):
        for route in dependency["routes"]:
            for link in route["chain"]:
                edges.add((link["importer"], link["imported"]))

    # forbidden: invalid_chains -> chains -> links
    for invalid in metadata.get("invalid_chains", []):
        for chain in invalid["chains"]:
            for link in chain:
                edges.add((link["importer"], link["imported"]))

    # acyclic_siblings: {package: {(importer, imported)}}
    for breakers in metadata.get("cycle_breakers_by_package", {}).values():
        edges.update(breakers)

    return sorted(f"{importer} -> {imported}" for importer, imported in edges)


def measure(text: str) -> dict[str, list[str]]:
    """Run the contracts with no baselines and return every violation they find."""
    sys.path.insert(0, str(Path.cwd()))
    try:
        from importlinter.api import read_configuration
        from importlinter.application.use_cases import (
            _register_contract_types,
            create_report,
        )
        from importlinter.application.user_options import UserOptions
    except Exception as exc:  # pragma: no cover - depends on the installed version
        raise ConfigShapeError(f"import-linter is not usable here: {exc!r}") from exc

    with tempfile.TemporaryDirectory(prefix="boundary-baseline-") as raw:
        path = Path(raw) / ".importlinter"
        path.write_text(strip_baselines(text))
        try:
            parsed = read_configuration(str(path))
        except Exception as exc:
            raise ConfigShapeError(
                f"the declarations could not be parsed: {exc!r}"
            ) from exc
        options = UserOptions(parsed["session_options"], parsed["contracts_options"])

        missing = [
            contract_id
            for contract_id in CONTRACT_IDS
            if contract_id not in [c.get("id") for c in options.contracts_options]
        ]
        if missing:
            raise ConfigShapeError(
                f"the declarations are missing {missing}; refusing to write a "
                "baseline for a check that no longer runs them"
            )

        try:
            _register_contract_types(options)
            report = create_report(options, cache_dir=None)
        except Exception as exc:
            raise ConfigShapeError(f"the contracts could not be run: {exc!r}") from exc

        if report.could_not_run:
            raise ConfigShapeError("import-linter could not run one of the contracts")

        # The report holds the contracts in declaration order (and a contract
        # that could not be built returns early, which the check above caught),
        # so the ids line up with the options the report was built from.
        checks = list(report.get_contracts_and_checks())
        declared = [c["id"] for c in options.contracts_options]
        if len(checks) != len(declared):
            raise ConfigShapeError(
                f"{len(checks)} contract(s) ran but {len(declared)} were declared; "
                "refusing to guess which baseline belongs to which"
            )
        return {
            contract_id: entries_from_metadata(check.metadata)
            for contract_id, (_, check) in zip(declared, checks, strict=True)
        }


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--config", default=str(CONFIG_PATH))
    parser.add_argument(
        "--update",
        action="store_true",
        help="write the refreshed baseline (without it this only reports)",
    )
    parser.add_argument(
        "--dry-run", action="store_true", help="report what would change, write nothing"
    )
    parser.add_argument(
        "--freeze-new",
        action="store_true",
        help="also freeze violations that are not in the baseline yet, printing them",
    )
    args = parser.parse_args()

    config_path = Path(args.config)
    if not (Path.cwd() / "app" / "__init__.py").is_file():
        print(
            f"cannot judge: no app/ package in {Path.cwd()} — run this from the "
            "directory that holds it (backend/)",
            file=sys.stderr,
        )
        return CANNOT_JUDGE

    try:
        text = config_path.read_text()
        old = read_entries(text)
        new = measure(text)
    except ConfigShapeError as exc:
        print(f"cannot judge: {exc}", file=sys.stderr)
        return CANNOT_JUDGE
    except FileNotFoundError:
        print(f"cannot judge: no {config_path} to read", file=sys.stderr)
        return CANNOT_JUDGE

    changes = False
    blocked: list[str] = []
    for contract_id in sorted(new):
        before, after = set(old.get(contract_id, ())), set(new[contract_id])
        added, removed = sorted(after - before), sorted(before - after)
        if removed:
            changes = True
            print(
                f"{contract_id}: dropping {len(removed)} entry that no longer matches"
            )
            for entry in removed:
                print(f"  - {entry}")
        if added:
            changes = True
            if args.freeze_new:
                print(f"{contract_id}: freezing {len(added)} new violation(s)")
                for entry in added:
                    print(f"  + {entry}")
            else:
                blocked.extend(f"[{contract_id}] {entry}" for entry in added)

    if blocked:
        print(
            f"\n{len(blocked)} new violation(s) this baseline does not have. "
            "These are the thing the check exists to catch — fix them, or freeze "
            "them on purpose with --freeze-new:\n" + "\n".join(blocked),
            file=sys.stderr,
        )
        return NEEDS_DECISION

    if not changes:
        print(f"unchanged: {config_path.name} still matches the tree")
        return OK

    if not args.update:
        print(
            f"{config_path.name} would be rewritten, nothing written "
            "(pass --update to write)"
        )
        return OK

    original = text
    config_path.write_text(write_baselines(text, new))

    # A refresh that leaves the check red looks like it worked, so verify it.
    import subprocess

    result = subprocess.run(
        [
            sys.executable,
            str(HERE.parent / "check_boundaries.py"),
            "--config",
            str(config_path),
        ],
        cwd=Path.cwd(),
        capture_output=True,
        text=True,
    )
    if result.returncode != OK:
        config_path.write_text(original)
        print(
            "cannot judge: the rewritten baseline does not converge — "
            f"check_boundaries.py exited {result.returncode} and the original "
            f"{config_path.name} has been restored\n{result.stdout}{result.stderr}",
            file=sys.stderr,
        )
        return CANNOT_JUDGE

    total = sum(len(entries) for entries in new.values())
    print(
        f"wrote {config_path.name}: {total} frozen entries across {len(new)} contracts"
    )
    return OK


if __name__ == "__main__":
    sys.exit(main())
