"""Model identity probe: is each model really the model it is billed as?

The platform binds a seat to a model and signs that claim into a credential; a
turn's card and its ``agent_turns.route`` record what the binding said. Nothing
in that chain looks at what actually generated the tokens. FB-73 is what that
gap costs: a session rebuilt after a disconnect was issued its credential for
the *project default* seat, so a turn signed as one model was generated by
another, and both the card and the route row kept the claim.

This package answers the question the card cannot answer for itself. Three
signals, none of which is the model's own testimony:

* ``tokenizer_fp``  the server's billed ``input_tokens`` for a fixed probe
  minus a fixed base -- the tokenizer a request passed through.
* ``report.build_provenance``  what the response said on the wire: which pool's
  headers came back, and which upstream name the gateway recorded.
* ``battery`` + ``stats`` + ``verdict``  the one-token answer distribution,
  compared against a reference collected from a trusted endpoint
  (Bruckner, "One Token Is Enough", arXiv:2607.10252; the probe battery and the
  normalisation pipeline are ported from ``llm-fingerprint-detector``, MIT,
  Copyright (c) 2026 Tosea.ai and contributors).

Two honest boundaries, both inherited from the literature:

* ``llm-api-audit`` (arXiv:2504.04715) concludes that pure software detection
  cannot reliably catch an *adversarial* provider; only hardware attestation
  can. What these signals do catch is the accident -- a mis-set credential, a
  stale binding, a routing seam -- which is exactly what FB-73 was.
* Fingerprints drift as a provider updates a checkpoint, so a reference must be
  refreshed; every model here is absent from every published fingerprint set,
  so references are built locally and record the endpoint they came from.
"""

from .stats import (
    JSD_MATCH_THRESHOLD,
    JSD_MISMATCH_THRESHOLD,
    PROBE_PROTOCOL,
)

__all__ = ["JSD_MATCH_THRESHOLD", "JSD_MISMATCH_THRESHOLD", "PROBE_PROTOCOL"]
