"""block node_type and struct_order for doc tree

Revision ID: fa00b8cc7375
Revises: b21d83d491c7
Create Date: 2026-06-30 18:44:54.109114

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "fa00b8cc7375"
down_revision: str | Sequence[str] | None = "b21d83d491c7"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("blocks", sa.Column("node_type", sa.String(length=16), nullable=True))
    op.add_column("blocks", sa.Column("struct_order", sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("blocks", "struct_order")
    op.drop_column("blocks", "node_type")
    # ### end Alembic commands ###
