"""add notification.resolved_at + project.last_heartbeat_at

Revision ID: b21d83d491c7
Revises: b1039d7b8f40
Create Date: 2026-06-16 14:27:32.366446

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b21d83d491c7"
down_revision: str | Sequence[str] | None = "b1039d7b8f40"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "notifications",
        sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=True),
    )
    op.add_column(
        "projects",
        sa.Column("last_heartbeat_at", sa.DateTime(timezone=True), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("projects", "last_heartbeat_at")
    op.drop_column("notifications", "resolved_at")
    # ### end Alembic commands ###
