"""fix_user_id_autoincrement

Revision ID: 718ecf7d61d9
Revises: c3a1b2d4e5f6
Create Date: 2026-05-02 19:41:04.971810

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "718ecf7d61d9"
down_revision: str | Sequence[str] | None = "c3a1b2d4e5f6"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "invite_code",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "task_submission_entry",
        "content_attachment_id",
        existing_type=sa.INTEGER(),
        comment="References attachment.id; kept nullable for pure-text entries.",
        existing_nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "task_submission_entry",
        "content_attachment_id",
        existing_type=sa.INTEGER(),
        comment=None,
        existing_comment="References attachment.id; kept nullable for pure-text entries.",
        existing_nullable=True,
    )
    op.alter_column(
        "invite_code",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.create_table(
        "spatial_ref_sys",
        sa.Column("srid", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("auth_name", sa.VARCHAR(length=256), autoincrement=False, nullable=True),
        sa.Column("auth_srid", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("srtext", sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
        sa.Column("proj4text", sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
        sa.CheckConstraint("srid > 0 AND srid <= 998999", name=op.f("spatial_ref_sys_srid_check")),
        sa.PrimaryKeyConstraint("srid", name=op.f("spatial_ref_sys_pkey")),
    )
    # ### end Alembic commands ###
