"""create_topic_table

Revision ID: fc51061dd06b
Revises: 28c58249b703
Create Date: 2026-05-02 22:42:25.634323

"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "fc51061dd06b"
down_revision: str | Sequence[str] | None = "28c58249b703"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.execute("""
        DO $$
        BEGIN
            IF NOT EXISTS (SELECT 1 FROM pg_tables WHERE tablename = 'topic') THEN
                CREATE TABLE topic (
                    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                    name VARCHAR NOT NULL,
                    created_by_id BIGINT NOT NULL,
                    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
                    deleted_at TIMESTAMP WITHOUT TIME ZONE
                );
            END IF;
        END
        $$;
    """)


def downgrade() -> None:
    op.execute("DROP TABLE IF EXISTS topic")
