"""create_topic_table

Revision ID: fc51061dd06b
Revises: 9b3dbc5ade4c
Create Date: 2026-05-02 22:42:25.634323

"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "fc51061dd06b"
down_revision: str | Sequence[str] | None = "9b3dbc5ade4c"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # 创建 topic 表（如果不存在）
    op.execute("""
        CREATE TABLE IF NOT EXISTS topic (
            id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
            name VARCHAR NOT NULL,
            created_by_id BIGINT NOT NULL,
            created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
            deleted_at TIMESTAMP WITHOUT TIME ZONE
        )
    """)
    # 如果需要索引可以加，但模型里没有定义索引，暂时不加


def downgrade() -> None:
    # 注意：DROP TABLE 会级联删除依赖对象，谨慎，但测试环境可接受
    op.execute("DROP TABLE IF EXISTS topic")
