"""block turn_id for per-turn traceability

Revision ID: 4f9b64cd1d48
Revises: fa00b8cc7375
Create Date: 2026-07-01 03:35:23.287661

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4f9b64cd1d48"
down_revision: str | Sequence[str] | None = "fa00b8cc7375"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("blocks", sa.Column("turn_id", sa.Uuid(), nullable=True))
    op.create_index(op.f("ix_blocks_turn_id"), "blocks", ["turn_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_blocks_turn_id"), table_name="blocks")
    op.drop_column("blocks", "turn_id")
    # ### end Alembic commands ###
