"""project summary one-pager

Revision ID: 4f9d5a47356e
Revises: cf93e4735e4a
Create Date: 2026-06-15 13:43:11.564220

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4f9d5a47356e'
down_revision: Union[str, Sequence[str], None] = 'cf93e4735e4a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('summary', sa.Text(), server_default='', nullable=False))
    op.create_foreign_key('fk_projects_root_topic_id', 'projects', 'topics', ['root_topic_id'], ['id'], ondelete='SET NULL', use_alter=True)
    op.create_foreign_key('fk_topics_upgraded_from_block_id', 'topics', 'blocks', ['upgraded_from_block_id'], ['id'], ondelete='SET NULL', use_alter=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_topics_upgraded_from_block_id', 'topics', type_='foreignkey')
    op.drop_constraint('fk_projects_root_topic_id', 'projects', type_='foreignkey')
    op.drop_column('projects', 'summary')
    # ### end Alembic commands ###
