"""fix_user_id_autoincrement

Revision ID: 718ecf7d61d9
Revises: 99da558b24a8
Create Date: 2026-05-02 19:41:04.971810

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "718ecf7d61d9"
down_revision: str | Sequence[str] | None = "99da558b24a8"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        'ALTER TABLE "user" ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY'
    )
    op.execute(
        "SELECT setval(pg_get_serial_sequence('user', 'id'), COALESCE((SELECT MAX(id) FROM \"user\"), 0) + 1, false)"  # noqa: E501
    )
    op.alter_column(
        "invite_code",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "task_submission_entry",
        "content_attachment_id",
        existing_type=sa.INTEGER(),
        comment="References attachment.id; kept nullable for pure-text entries.",
        existing_nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('ALTER TABLE "user" ALTER COLUMN id DROP IDENTITY IF EXISTS')
    op.alter_column(
        "task_submission_entry",
        "content_attachment_id",
        existing_type=sa.INTEGER(),
        comment=None,
        existing_comment="References attachment.id; kept nullable for pure-text entries.",  # noqa: E501
        existing_nullable=True,
    )
    op.alter_column(
        "invite_code",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    # ### end Alembic commands ###
