"""topic private chat fields

Revision ID: 98723b7a3b87
Revises: 4f9d5a47356e
Create Date: 2026-06-15 14:40:31.791678

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '98723b7a3b87'
down_revision: Union[str, Sequence[str], None] = '4f9d5a47356e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('topics', sa.Column('is_private', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('topics', sa.Column('private_owner', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('topics', 'private_owner')
    op.drop_column('topics', 'is_private')
    # ### end Alembic commands ###
