"""full schema

Revision ID: cf93e4735e4a
Revises: 
Create Date: 2026-06-15 00:52:38.599954

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cf93e4735e4a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('memory_entries',
    sa.Column('scope', sa.Enum('project', 'user', 'skill', name='memoryscope', native_enum=False, length=16), nullable=False),
    sa.Column('scope_id', sa.String(length=128), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_memory_entries_scope'), 'memory_entries', ['scope'], unique=False)
    op.create_index(op.f('ix_memory_entries_scope_id'), 'memory_entries', ['scope_id'], unique=False)
    op.create_table('projects',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('owner_handle', sa.String(length=64), nullable=True),
    sa.Column('ai_mode', sa.Enum('autonomous', 'collaborative', name='aimode', native_enum=False, length=16), nullable=False),
    sa.Column('root_topic_id', sa.Uuid(), nullable=True),
    sa.Column('expert_role', sa.String(length=64), nullable=True),
    sa.Column('settings', sa.JSON(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['root_topic_id'], ['topics.id'], name='fk_projects_root_topic_id', ondelete='SET NULL', use_alter=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('spaces',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('kind', sa.Enum('college', 'school', 'company', 'other', name='spacekind', native_enum=False, length=16), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('handle', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.Column('bio', sa.Text(), nullable=False),
    sa.Column('interests', sa.JSON(), nullable=False),
    sa.Column('skills', sa.JSON(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_handle'), 'users', ['handle'], unique=True)
    op.create_table('expert_roles',
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('role_description', sa.Text(), nullable=False),
    sa.Column('skills', sa.JSON(), nullable=False),
    sa.Column('is_preset', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_expert_roles_name'), 'expert_roles', ['name'], unique=False)
    op.create_index(op.f('ix_expert_roles_project_id'), 'expert_roles', ['project_id'], unique=False)
    op.create_table('project_members',
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('user_handle', sa.String(length=64), nullable=False),
    sa.Column('role', sa.Enum('lead', 'member', 'mentor', name='projectrole', native_enum=False, length=16), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'user_handle', name='uq_project_member')
    )
    op.create_index(op.f('ix_project_members_project_id'), 'project_members', ['project_id'], unique=False)
    op.create_index(op.f('ix_project_members_user_handle'), 'project_members', ['user_handle'], unique=False)
    op.create_table('task_templates',
    sa.Column('space_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('resource_pack', sa.JSON(), nullable=False),
    sa.Column('conditions', sa.JSON(), nullable=False),
    sa.Column('default_role', sa.String(length=64), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['space_id'], ['spaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_task_templates_space_id'), 'task_templates', ['space_id'], unique=False)
    op.create_table('topics',
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('parent_id', sa.Uuid(), nullable=True),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('kind', sa.Enum('root', 'topic', 'subtopic', name='topickind', native_enum=False, length=16), nullable=False),
    sa.Column('status', sa.Enum('active', 'archived', 'draft', name='topicstatus', native_enum=False, length=16), nullable=False),
    sa.Column('session_id', sa.String(length=128), nullable=True),
    sa.Column('branch_name', sa.String(length=200), nullable=True),
    sa.Column('created_by', sa.String(length=64), nullable=True),
    sa.Column('upgraded_from_block_id', sa.Uuid(), nullable=True),
    sa.Column('accepted_by', sa.String(length=64), nullable=True),
    sa.Column('accepted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['topics.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['upgraded_from_block_id'], ['blocks.id'], name='fk_topics_upgraded_from_block_id', ondelete='SET NULL', use_alter=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_topics_parent_id'), 'topics', ['parent_id'], unique=False)
    op.create_index(op.f('ix_topics_project_id'), 'topics', ['project_id'], unique=False)
    op.create_table('accept_cards',
    sa.Column('topic_id', sa.Uuid(), nullable=False),
    sa.Column('reviewer_handle', sa.String(length=64), nullable=False),
    sa.Column('routing_reason', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'accepted', 'rejected', 'revoked', name='acceptstatus', native_enum=False, length=16), nullable=False),
    sa.Column('decided_by', sa.String(length=64), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('note', sa.Text(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_accept_cards_reviewer_handle'), 'accept_cards', ['reviewer_handle'], unique=False)
    op.create_index(op.f('ix_accept_cards_topic_id'), 'accept_cards', ['topic_id'], unique=False)
    op.create_table('blocks',
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('topic_id', sa.Uuid(), nullable=False),
    sa.Column('kind', sa.Enum('message', 'doc', 'decision', 'attachment', 'event', name='blockkind', native_enum=False, length=16), nullable=False),
    sa.Column('author_type', sa.Enum('human', 'ai', 'system', name='authortype', native_enum=False, length=16), nullable=False),
    sa.Column('author', sa.String(length=128), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('reply_to', sa.Uuid(), nullable=True),
    sa.Column('struct_parent', sa.Uuid(), nullable=True),
    sa.Column('refs', sa.JSON(), nullable=False),
    sa.Column('upgraded_to_topic_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reply_to'], ['blocks.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['struct_parent'], ['blocks.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['upgraded_to_topic_id'], ['topics.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_blocks_project_id'), 'blocks', ['project_id'], unique=False)
    op.create_index(op.f('ix_blocks_reply_to'), 'blocks', ['reply_to'], unique=False)
    op.create_index(op.f('ix_blocks_struct_parent'), 'blocks', ['struct_parent'], unique=False)
    op.create_index(op.f('ix_blocks_topic_id'), 'blocks', ['topic_id'], unique=False)
    op.create_table('milestones',
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('due_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('upcoming', 'done', 'missed', name='milestonestatus', native_enum=False, length=16), nullable=False),
    sa.Column('source_topic_id', sa.Uuid(), nullable=True),
    sa.Column('auto_pinned', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_topic_id'], ['topics.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_milestones_project_id'), 'milestones', ['project_id'], unique=False)
    op.create_table('notifications',
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('topic_id', sa.Uuid(), nullable=True),
    sa.Column('level', sa.Enum('silent', 'light', 'strong', name='notiflevel', native_enum=False, length=16), nullable=False),
    sa.Column('kind', sa.Enum('change_alert', 'decision_request', 'accept_request', 'heartbeat', name='notifkind', native_enum=False), nullable=False),
    sa.Column('target_handle', sa.String(length=64), nullable=True),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('feedback', sa.String(length=8), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_project_id'), 'notifications', ['project_id'], unique=False)
    op.create_index(op.f('ix_notifications_target_handle'), 'notifications', ['target_handle'], unique=False)
    op.create_index(op.f('ix_notifications_topic_id'), 'notifications', ['topic_id'], unique=False)
    op.create_table('tasks',
    sa.Column('template_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['template_id'], ['task_templates.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tasks_template_id'), 'tasks', ['template_id'], unique=False)
    op.create_table('project_task_links',
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('task_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'task_id', name='uq_project_task')
    )
    op.create_index(op.f('ix_project_task_links_project_id'), 'project_task_links', ['project_id'], unique=False)
    op.create_index(op.f('ix_project_task_links_task_id'), 'project_task_links', ['task_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_project_task_links_task_id'), table_name='project_task_links')
    op.drop_index(op.f('ix_project_task_links_project_id'), table_name='project_task_links')
    op.drop_table('project_task_links')
    op.drop_index(op.f('ix_tasks_template_id'), table_name='tasks')
    op.drop_table('tasks')
    op.drop_index(op.f('ix_notifications_topic_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_target_handle'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_project_id'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_milestones_project_id'), table_name='milestones')
    op.drop_table('milestones')
    op.drop_index(op.f('ix_blocks_topic_id'), table_name='blocks')
    op.drop_index(op.f('ix_blocks_struct_parent'), table_name='blocks')
    op.drop_index(op.f('ix_blocks_reply_to'), table_name='blocks')
    op.drop_index(op.f('ix_blocks_project_id'), table_name='blocks')
    op.drop_table('blocks')
    op.drop_index(op.f('ix_accept_cards_topic_id'), table_name='accept_cards')
    op.drop_index(op.f('ix_accept_cards_reviewer_handle'), table_name='accept_cards')
    op.drop_table('accept_cards')
    op.drop_index(op.f('ix_topics_project_id'), table_name='topics')
    op.drop_index(op.f('ix_topics_parent_id'), table_name='topics')
    op.drop_table('topics')
    op.drop_index(op.f('ix_task_templates_space_id'), table_name='task_templates')
    op.drop_table('task_templates')
    op.drop_index(op.f('ix_project_members_user_handle'), table_name='project_members')
    op.drop_index(op.f('ix_project_members_project_id'), table_name='project_members')
    op.drop_table('project_members')
    op.drop_index(op.f('ix_expert_roles_project_id'), table_name='expert_roles')
    op.drop_index(op.f('ix_expert_roles_name'), table_name='expert_roles')
    op.drop_table('expert_roles')
    op.drop_index(op.f('ix_users_handle'), table_name='users')
    op.drop_table('users')
    op.drop_table('spaces')
    op.drop_table('projects')
    op.drop_index(op.f('ix_memory_entries_scope_id'), table_name='memory_entries')
    op.drop_index(op.f('ix_memory_entries_scope'), table_name='memory_entries')
    op.drop_table('memory_entries')
    # ### end Alembic commands ###
