// Package cliapp builds the 'cheese' CLI as a urfave/cli/v2 App. All
// help/usage/version text is generated by the urfave/cli library itself
// (contract §7) — this package only supplies Usage/ArgsUsage/Description
// strings and command wiring; it must never hand-roll fmt.Printf help.
package cliapp

import (
	"encoding/json"
	"fmt"

	"cheese/connector/cheese/internal/client"

	"github.com/urfave/cli/v2"
)

// Version is the cheese CLI version, reported by 'cheese --version'.
// Overridable at link time: -ldflags "-X cheese/connector/cheese/internal/cliapp.Version=..."
var Version = "0.1.0"

const defaultDaemonURL = "http://127.0.0.1:47615"

// daemonFactory constructs a Daemon for a given base URL. It is a variable
// (rather than a direct call to client.New) so tests can substitute a fake
// daemon.
var daemonFactory = func(baseURL string) client.Daemon {
	return client.New(baseURL)
}

// New constructs the cheese cli.App. main.go should do nothing but call
// New(...).Run(os.Args).
func New() *cli.App {
	app := &cli.App{
		Name:  "cheese",
		Usage: "AI-friendly wrapper CLI over cheesed's local tool-RPC API",
		Description: "cheese talks to a locally running cheesed daemon over HTTP to discover\n" +
			"and invoke the tools that the cheese-backend orchestrator exposes to the\n" +
			"agent (see contract §6-7). It has no state of its own; every command is a\n" +
			"single request/response round trip to the daemon.",
		Version: Version,
		Flags: []cli.Flag{
			&cli.StringFlag{
				Name:    "daemon-url",
				Aliases: []string{"u"},
				Usage:   "base URL of the local cheesed daemon HTTP API",
				Value:   defaultDaemonURL,
				EnvVars: []string{"CHEESE_DAEMON_URL"},
			},
		},
		Commands: []*cli.Command{
			schemaCommand(),
			callCommand(),
		},
	}
	return app
}

func daemonFromContext(c *cli.Context) client.Daemon {
	return daemonFactory(c.String("daemon-url"))
}

func schemaCommand() *cli.Command {
	return &cli.Command{
		Name:      "schema",
		Usage:     "print the tool schema exposed by the connected backend",
		ArgsUsage: " ",
		Description: "Fetches GET /schema from the cheesed daemon (which proxies\n" +
			"GET /connector/tools/schema on the backend) and prints the resulting\n" +
			"JSON tool-definition list to stdout.",
		Action: func(c *cli.Context) error {
			d := daemonFromContext(c)
			data, err := d.Schema(c.Context)
			if err != nil {
				return cli.Exit(fmt.Sprintf("cheese: schema: %v", err), 1)
			}
			fmt.Fprintln(c.App.Writer, string(client.PrettyJSON(data)))
			return nil
		},
	}
}

func callCommand() *cli.Command {
	return &cli.Command{
		Name:      "call",
		Usage:     "invoke a tool by name via the daemon",
		ArgsUsage: "<tool>",
		Description: "Posts to /call?tool=<tool> on the cheesed daemon (which proxies\n" +
			"POST /connector/tools/call?tool=<tool> on the backend) with the given\n" +
			"--args JSON object as the request body, and prints the JSON result.\n" +
			"Exits with a non-zero status if the tool call fails.",
		Flags: []cli.Flag{
			&cli.StringFlag{
				Name:  "args",
				Usage: "JSON object of arguments to pass to the tool",
				Value: "{}",
			},
		},
		Action: func(c *cli.Context) error {
			tool := c.Args().First()
			if tool == "" {
				return cli.Exit("cheese: call: missing required argument <tool>", 1)
			}
			if c.NArg() > 1 {
				return cli.Exit(fmt.Sprintf("cheese: call: unexpected extra arguments: %v", c.Args().Slice()[1:]), 1)
			}

			argsJSON := []byte(c.String("args"))
			if len(argsJSON) > 0 {
				var probe json.RawMessage
				if err := json.Unmarshal(argsJSON, &probe); err != nil {
					return cli.Exit(fmt.Sprintf("cheese: call: --args is not valid JSON: %v", err), 1)
				}
			}

			d := daemonFromContext(c)
			data, err := d.Call(c.Context, tool, argsJSON)
			if err != nil {
				if len(data) > 0 {
					fmt.Fprintln(c.App.ErrWriter, string(client.PrettyJSON(data)))
				}
				return cli.Exit(fmt.Sprintf("cheese: call: %v", err), 1)
			}
			fmt.Fprintln(c.App.Writer, string(client.PrettyJSON(data)))
			return nil
		},
	}
}
