#!/usr/bin/env bash
# Point api-front's preview tunnel at the right upstream for the current mode.
#
# The machine's preview tunnel (both /preview/tunnel and /api/preview/tunnel)
# is dialed at the box's public origin. nginx.conf routes it to the variable
# $preview_tunnel_upstream, whose value this file sets:
#   owner  -> the independently released preview-connection owner
#   legacy -> the active business backend through app-router, i.e. exactly the
#             path every other request took before the cutover
# Only the routing target moves here; the location itself lives in nginx.conf,
# so reverting that file removes the route and the tunnel falls through to the
# business backend again.
#
# This prepares configuration only; the deploy validates and reloads nginx.
set -euo pipefail

MODE="${1:?usage: configure-preview.sh owner|legacy [ACTIVE_DIRECTORY] [OWNER_PORT]}"
ACTIVE_DIR="${2:-${ACTIVE_BACKEND_DIR:-$(dirname "$0")/active}}"
OWNER_PORT="${3:-18087}"
# The persistent app-router in front of the backend (nginx.conf's
# backend_active). Legacy targets this, not a backend container port, so the
# tunnel keeps the same lifecycle as every other business request.
BACKEND_PORT="${4:-18085}"

case "$MODE" in
  owner|legacy) ;;
  *) echo "Mode must be owner or legacy, not '$MODE'." >&2; exit 1 ;;
esac
for port in "$OWNER_PORT" "$BACKEND_PORT"; do
  [[ "$port" =~ ^[0-9]+$ ]] && ((port > 0 && port < 65536)) || { echo "Invalid port: $port" >&2; exit 1; }
done

if [[ "$MODE" = owner ]]; then
  TARGET="127.0.0.1:$OWNER_PORT"
else
  TARGET="127.0.0.1:$BACKEND_PORT"
fi

mkdir -p "$ACTIVE_DIR"
CONFIG_TMP="$(mktemp "$ACTIVE_DIR/.preview-routing.XXXXXX")"
trap 'rm -f "$CONFIG_TMP"' EXIT
cat > "$CONFIG_TMP" <<EOF
# Generated by deploy/llm-tunnel/configure-preview.sh — do not edit.
# The preview tunnel route in nginx.conf reads \$preview_tunnel_upstream.
map \$host \$preview_tunnel_upstream {
  default "$TARGET";
}
EOF
# The mounted directory observes this rename without recreating the container.
mv -f "$CONFIG_TMP" "$ACTIVE_DIR/preview-routing.conf"
printf 'Prepared %s/preview-routing.conf (%s -> %s); nginx has not been reloaded.\n' \
  "$ACTIVE_DIR" "$MODE" "$TARGET"
